#!/usr/bin/env python3
"""
SIMPLE CHAT PROCESSOR - Actually works without timeouts
Just processes your chat logs into documentation and AI tasks
"""

import os
import json
import re
from datetime import datetime

def process_chat_log_file(input_file):
    """Process a chat log file directly"""
    
    # Read the chat log
    with open(input_file, 'r') as f:
        content = f.read()
    
    # Extract filename without extension
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Create output directories
    os.makedirs("generated_docs", exist_ok=True)
    os.makedirs("ai_tasks", exist_ok=True)
    
    # Analyze content
    analysis = analyze_content(content)
    
    # Generate documentation
    doc = generate_documentation(analysis, base_name)
    
    # Generate AI tasks
    tasks = generate_ai_tasks(analysis, base_name)
    
    # Save files
    doc_file = f"generated_docs/{base_name}_{timestamp}_docs.md"
    tasks_file = f"ai_tasks/{base_name}_{timestamp}_tasks.json"
    
    with open(doc_file, 'w') as f:
        f.write(doc)
    
    with open(tasks_file, 'w') as f:
        json.dump(tasks, f, indent=2)
    
    print(f"""
✅ CHAT LOG PROCESSED!

📄 Documentation: {doc_file}
🎯 AI Tasks: {tasks_file}

📊 ANALYSIS:
- Code blocks found: {len(analysis['code_blocks'])}
- Files mentioned: {len(analysis['files'])}
- User requests: {len(analysis['requests'])}
- Errors found: {len(analysis['errors'])}
- Technologies: {len(analysis['tech'])}

🚀 NEXT STEPS:
1. Review the documentation file
2. Send tasks from the JSON file to:
   - Claude Code CLI
   - Cal Riven
   - Codex CLI
3. Iterate until everything works
""")
    
    return doc_file, tasks_file

def analyze_content(content):
    """Simple but effective content analysis"""
    
    # Extract code blocks
    code_blocks = re.findall(r'```(\w+)?\n(.*?)\n```', content, re.DOTALL)
    
    # Extract file mentions
    files = re.findall(r'\b\w+\.(py|js|json|md|txt|ts|html|css)\b', content)
    
    # Extract user requests
    request_patterns = [
        r'(?:can you|could you|please|i want|i need|how do i|help me)\s+([^.!?]+)',
        r'(?:create|build|make|implement|add)\s+([^.!?]+)'
    ]
    requests = []
    for pattern in request_patterns:
        matches = re.findall(pattern, content, re.IGNORECASE)
        requests.extend([match.strip() for match in matches])
    
    # Extract errors
    errors = re.findall(r'(?:error|failed|exception|timeout)[:\s]+([^.!?\n]+)', content, re.IGNORECASE)
    
    # Extract technologies
    tech = re.findall(r'\b(python|javascript|typescript|react|vue|angular|docker|api|claude|codex|github)\b', content, re.IGNORECASE)
    
    return {
        'code_blocks': code_blocks,
        'files': list(set(files)),
        'requests': requests[:10],
        'errors': errors[:5],
        'tech': list(set(tech))
    }

def generate_documentation(analysis, filename):
    """Generate simple documentation"""
    
    doc = f"""# 📋 Documentation: {filename}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 🎯 Overview

This document was generated from your chat log about {filename}.

## 📁 Files Mentioned ({len(analysis['files'])})

"""
    for file in analysis['files']:
        doc += f"- `{file[0]}`\n"
    
    doc += f"""
## 🔧 Technologies Identified ({len(analysis['tech'])})

"""
    for tech in analysis['tech']:
        doc += f"- {tech}\n"
    
    doc += f"""
## 🎯 User Requests ({len(analysis['requests'])})

"""
    for i, request in enumerate(analysis['requests'], 1):
        doc += f"{i}. {request}\n"
    
    doc += f"""
## 💻 Code Blocks ({len(analysis['code_blocks'])})

"""
    for i, (lang, code) in enumerate(analysis['code_blocks'], 1):
        doc += f"### Block {i} ({lang or 'unknown'})\n```{lang or ''}\n{code.strip()}\n```\n\n"
    
    doc += f"""
## ⚠️ Errors Mentioned ({len(analysis['errors'])})

"""
    for error in analysis['errors']:
        doc += f"- {error.strip()}\n"
    
    doc += """
## 🚀 Next Steps

1. Review this documentation
2. Use the AI tasks file to implement solutions
3. Send tasks to Claude, Cal, Codex
4. Iterate until everything works in your ecosystem

---
*Generated by Simple Chat Processor*
"""
    
    return doc

def generate_ai_tasks(analysis, filename):
    """Generate AI agent tasks"""
    
    tasks = {
        'metadata': {
            'source': filename,
            'generated_at': datetime.now().isoformat()
        },
        'claude_tasks': [],
        'cal_tasks': [],
        'codex_tasks': []
    }
    
    # Claude tasks (implementation)
    if analysis['code_blocks']:
        tasks['claude_tasks'].append({
            'type': 'code_review_and_improve',
            'description': f"Review and improve {len(analysis['code_blocks'])} code blocks",
            'priority': 'high'
        })
    
    for request in analysis['requests'][:3]:
        tasks['claude_tasks'].append({
            'type': 'implement_feature',
            'description': f"Implement: {request}",
            'priority': 'medium'
        })
    
    # Cal tasks (architecture)
    if 'integration' in filename.lower() or any('integrate' in req.lower() for req in analysis['requests']):
        tasks['cal_tasks'].append({
            'type': 'design_architecture',
            'description': 'Design integration architecture for the ecosystem',
            'priority': 'high'
        })
    
    if analysis['tech']:
        tasks['cal_tasks'].append({
            'type': 'technology_integration',
            'description': f"Integrate technologies: {', '.join(analysis['tech'])}",
            'priority': 'medium'
        })
    
    # Codex tasks (optimization)
    if analysis['errors']:
        tasks['codex_tasks'].append({
            'type': 'fix_errors',
            'description': 'Fix identified errors and improve error handling',
            'priority': 'high',
            'errors': analysis['errors']
        })
    
    if analysis['code_blocks']:
        tasks['codex_tasks'].append({
            'type': 'optimize_code',
            'description': 'Optimize code for better performance and maintainability',
            'priority': 'medium'
        })
    
    return tasks

def main():
    """Main function - simple CLI interface"""
    
    print("""
💬 SIMPLE CHAT PROCESSOR

This tool processes your chat logs into:
1. Structured documentation 
2. AI agent tasks for Claude, Cal, Codex

Usage:
1. Save your chat log as a .txt file
2. Run: python3 SIMPLE_CHAT_PROCESSOR.py
3. Enter the filename when prompted
""")
    
    # Get input file
    input_file = input("Enter chat log filename (e.g., 'my_chat.txt'): ").strip()
    
    if not input_file:
        print("❌ No filename provided")
        return
    
    if not os.path.exists(input_file):
        print(f"❌ File '{input_file}' not found")
        print("\n💡 Create a text file with your chat log content first")
        return
    
    try:
        doc_file, tasks_file = process_chat_log_file(input_file)
        
        print(f"""
🎉 SUCCESS! Your chat log has been processed.

📖 Read the documentation: {doc_file}
🤖 Use the AI tasks: {tasks_file}

Your workflow:
1. Review the generated documentation
2. Copy tasks from the JSON file
3. Send Claude tasks to Claude Code CLI
4. Send Cal tasks to Cal Riven  
5. Send Codex tasks to Codex CLI
6. Iterate until your ecosystem works!
""")
        
    except Exception as e:
        print(f"❌ Error processing file: {e}")

if __name__ == '__main__':
    main()