export const promptBank = [
  "What is something you secretly wish for?",
  "Describe a moment you felt unstoppable.",
  "What burden do you carry silently?",
  "If you could relive one minute, which would it be?",
  "Who do you miss but don't reach out to?",
  "Describe the last thing that made you laugh uncontrollably.",
  "What do you fear losing the most?",
  "If you could only say one word today, what would it be?",
  "What truth are you avoiding?",
  "What moment made you believe in yourself?",
  "What feels heavy right now?",
  "What would you say to your younger self today?",
  "Who deserves more gratitude from you?",
  "Describe your most rebellious thought.",
  "What part of yourself feels most alive?",
  "What have you forgiven yourself for recently?",
  "If you disappeared tomorrow, what would you hope they remember?",
  "What dream have you quietly kept alive?",
  "What unfinished conversation lingers in your mind?",
  "What risk are you glad you took?",
  "What emotion do you rarely express?",
  "What song feels like a time machine for you?",
  "When did you feel most at peace recently?",
  "What unseen wound still aches?",
  "If fear wasn't a factor, what would you try today?",
  "What secret are you proud of keeping?",
  "Describe a moment you chose kindness over anger.",
  "What is one promise you intend to keep to yourself?",
  "If you could send a message to your future self, what would it say?",
  "What tiny detail made your day better recently?",
  "When did you last surprise yourself?",
  "Who are you becoming?",
  "What feels worth fighting for?",
  "What piece of advice do you wish you ignored?",
  "What small thing makes you irrationally happy?",
  "What silence felt louder than words?",
  "Where does your mind go when it wanders?",
  "Describe a time you felt truly seen.",
  "If you wrote a letter you’d never send, who would it be to?",
  "What thought keeps resurfacing lately?",
  "What part of you is still healing?",
  "Who or what brings you effortless joy?",
  "What are you quietly proud of?",
  "If you could freeze a moment forever, which would it be?",
  "What feeling have you been chasing lately?",
  "When was the last time you truly listened to yourself?",
  "What truth have you recently accepted?",
  "What part of your life feels underappreciated?",
  "What emotion feels like home to you?",
  "When did you last let go of control?",
  "Describe a time you chose faith over fear.",
  "What part of you refuses to give up?",
  "What moment felt like a turning point?",
  "If today was your last ordinary day, how would you spend it?"
];
